### ISSUE TITLE
nbhits completely off with faceted search

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/milli#186] opened 2021-05-04 18:15 UTC
Found on 0.2.0, may be older

When performing a search with a facet filter, the nb hits is completely off:
**with filter:**
![image](https://user-images.githubusercontent.com/28804882/117050094-7e937700-ad04-11eb-9dca-4c8122b31013.png)
**without filter:**
![image](https://user-images.githubusercontent.com/28804882/117050184-99fe8200-ad04-11eb-8013-5d05422ffcec.png)

My guess is that this comes from the candidates not being intersected with the facet candidates

**Comment by Kerollmops** [comment] 2021-05-05 09:23
My guess is that there is no "real" bug here as this is the expected behavior.

When you do a search without a filter, the criteria builder is given a no candidates to start with, the buckets of the first criterion are merged and correspond to the `nbHits`.

However, when you specify a filter the retained candidates are given to the criteria builder this time and every time the first criterion needs to do an iteration (pulling new candidates) it intersect them with the retain candidates provided.

In your example I think that when you do not filter, the first criterion is pulling only once the candidates and therefore only 68 candidates, no need to go deeper so the `nbHits` is exactly the cardinality of the first bucket ever pulled.

In the other hand, when you filter the candidates, this time the first bucket does not contain enough candidates for the search to be satisfied so a second bucket is pulled by the first criterion and those two buckets are merged, `nbHits` is set to 5883.

That is only my first guess, maybe I am wrong, we need to look more closely to this behavior.

**Comment by MarinPostma** [comment] 2021-05-05 09:33
I think this is definitely a bug, or at least not the desired behaviour, since a placeholder search with the same same filter return the same nbhits
![image](https://user-images.githubusercontent.com/28804882/117121918-cbb72d80-ad84-11eb-90f6-0b5ef51f6221.png)

I'm investigating further to see if the issue is only with the nbhits

**Comment by Kerollmops** [comment] 2021-05-05 10:13
That's indeed strange, I think it is because the `Initial` criterion [returns the bucket candidates](https://github.com/meilisearch/milli/blob/1207a058d0a68a1e25eb5a567647596bbeeebd41/milli/src/search/criteria/initial.rs#L16) (the filter retained candidates), the first "real" criterion that is running after the `Initial` one (`Words` by default) is then simply returning the bucket candidates that comes from above, without performing an intersection.

I think @LegendreM can help us choose the solution to this problem:
 - Can we simply intersect the candidates with the pulled bucket candidates?
 - Doing an intersection for each iteration of the underlying criteria?
 - Would it be better to do it to the first non-`Initial` criterion?

I think this bug is due to the `Initial` criterion that we introduced recently.

**Closed** 2021-05-24 11:23 UTC
